create table if not exists public.app_ratings (
  id bigint generated by default as identity primary key,
  visitor_hash text not null unique,
  rating smallint not null,
  feedback text,
  feedback_prompt text,
  page_path text,
  visit_count integer not null default 0,
  content_view_count integer not null default 0,
  first_submitted_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint app_ratings_rating_check check (rating between 1 and 5),
  constraint app_ratings_feedback_length_check check (feedback is null or char_length(feedback) <= 600),
  constraint app_ratings_feedback_prompt_check check (
    feedback_prompt is null or feedback_prompt in ('improvement', 'highlight')
  ),
  constraint app_ratings_page_path_length_check check (page_path is null or char_length(page_path) <= 240),
  constraint app_ratings_visit_count_check check (visit_count between 0 and 100000),
  constraint app_ratings_content_view_count_check check (content_view_count between 0 and 100000)
);

create index if not exists app_ratings_updated_at_idx
  on public.app_ratings (updated_at desc);

create index if not exists app_ratings_rating_updated_at_idx
  on public.app_ratings (rating, updated_at desc);

alter table public.app_ratings enable row level security;

revoke all on public.app_ratings from anon, authenticated;
grant select, insert, update, delete on public.app_ratings to service_role;
grant usage, select on sequence public.app_ratings_id_seq to service_role;
